<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="EMailApprovalExample.private"
                  targetNamespace="http://EMailApprovalExample/emailapprovalexample">
</wsdl:definitions>