<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://avosinternal.servicenow.com/attachment" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://avosinternal.servicenow.com/attachment" xmlns:types1="http://www.example.org/POCAttachement">
  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:import namespace="http://www.example.org/POCAttachement" schemaLocation="../schema/POCAttachement.xsd"/>
	</xs:schema>
  </wsdl:types>
  <wsdl:message name="attachmentRequest">
    <wsdl:part name="attachmentRequest" element="types1:Request">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="attachmentResponse">
    <wsdl:part name="attachmentResponse" element="types1:Response">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="POCAttachement">
    <wsdl:operation name="attachment">
      <wsdl:input message="tns:attachmentRequest">
    </wsdl:input>
      <wsdl:output message="tns:attachmentResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
